name: Update Stock Prices

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  update-stocks:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger stock update
        run: |
          curl -X POST https://augustana-college-sif-website-novrions-projects.vercel.app/api/stocks_scheduler